# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd28bd27853176d336372aeb6bae5bb7b899dd3088f38d8c1f97c1132be626cd9dd3badf164c27f4655a5aeaf6b90451d6e2a00ee11799d6fd8bec3505d019de

test:
  secret_key_base: 583c492d450895f03631e58c94750cd6721e7e1edd812014d208b916961a53844cd8f791d0cfe2d9a7e2b5b8a8d1882d4e0db18886d55111ad872495e2fc853e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
